"use strict";
let userName = "JoysMery";
let userAge = 19;
let isMember = true;
console.log("Data type of userName is -->" + typeof userName);
console.log("Data type of userAge is -->" + typeof userAge);
console.log("Data type of isMember is -->" + typeof isMember);
console.log("Name:", userName);
console.log("Age:", userAge);
console.log("Active:", isMember);
